#pragma once

#define LAND	0
#define OBSTACLE	1
#define FOOD	2

#define COLOR_OBSTACLE	BACKGROUND_RED | BACKGROUND_INTENSITY
#define COLOR_FOOD		BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define COLOR_SNAKE		BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define COLOR_TEXT	FOREGROUND_RED | BACKGROUND_INTENSITY